# Generated by Django 3.0.1 on 2020-02-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_rec',
            new_name='order_recv',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_fee',
            field=models.IntegerField(default=20),
        ),
    ]
